name: Aljoscharei Anesthesia
description: Thinking about learning and knowing
meta_description: "Think more know less"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: "/aljoscharei"
domain_name: "https://aljoscharei.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Aljoscharei"

# Disqus config
disqus-shortname: ""
